language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SYMFONY_VERSION=2.7.*
        - php: 7.1
          env: SYMFONY_VERSION=2.8.*

before_install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
    - composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpspec run
    - vendor/bin/behat --format=progress
